### ISSUE TITLE
The library detects touch devices as without touch capabilities

### ISSUE THREAD

**Issue by romangit** [aichi/Touchr#10]
There are many workstations, such as Lenovo Thinkpad 460, 470, 480, 490, etc., which have touch capabilities, but do not have the `ontouchstart` property in the global `window` object, which is used in the library as a check for this. Therefore, the library does not work correctly. 

I want to note that in this case the result of code execution `!!window.navigator.maxTouchPoints` is `true`. In my case `window.navigator.maxTouchPoints` is `10`.

Please make changes to check touch capabilities.

**Comment by aichi** [comment]
Hi, thanks for opening this issue. To proceed forward can you please clarify in which browser + version and Windows + version the detection doesn't work? 

Can you please prepare also Pull Request with required change? Thanks.

**Comment by romangit** [comment]
Hi, 
Browser: Google Chrome, Version 77.0.3865.120 (Official Build) (64-bit)
OS: Windows 10 Pro
I will prepare a Pull Request in the near future

**Comment by aichi** [comment]
Thanks for reaching back with affected browser.
I think there is some miscommunication happened. This library is a drop in polyfill for supporting touchstart/.../end events in InternetExplorer and Microsoft Edge. So it is correct that it doesn't detect Chrome as these events are natively supported in it. 
If that wasn't clear from description, I am open to improvements in that area.
