### ISSUE TITLE
Touchr does not work in Edge 16/Windows 10 Fall Creators Update

### ISSUE THREAD

**Issue by martinsuchan** [aichi/Touchr#7]
There is a bug in pointer events detection logic:
```
var IE_10		= !!window.navigator.msPointerEnabled,
// Check below can mark as IE11+ also other browsers which implements pointer events in future
// that is not issue, because touch capability is tested in IF statement bellow.
IE_11_PLUS	= !!window.navigator.pointerEnabled;
```

**window.navigator.pointerEnabled** was deprecated in many browsers some time ago, see:  
https://webplatform.github.io/docs/dom/Navigator/pointerEnabled/
http://www.html5gamedevs.com/topic/25991-warning-navigatorpointerenabled-depricated/

On Windows 10 Creators Update/1703 it returns **true**, but
on Windows 10 Fall Creators Update/1709 it returns **undefined**, so the pointer events won't work.
Simple test: https://jsfiddle.net/a4ca9j0u/

Fix could be something like this:
```
if (window.PointerEvent || window.MSPointerEvent || window.navigator.msPointerEnabled || window.navigator.pointerEnabled)
{
    device.mspointer = true;
}
```

**Comment by aichi** [comment]
Hi Martin, can you please prepare it as pull request? I will merge it

**Comment by martinsuchan** [comment]
I can change the line https://github.com/aichi/Touchr/blob/master/js/touchr.js#L15 to:
`IE_11_PLUS	= !!window.navigator.pointerEnabled || window.PointerEvent;`
That works on latest Edge 16 just fine.

The problem is, this returns in Chrome and Firefox 'true' as well. My question is how is touchr.js suppose to work in browsers that supports both Touch events and Pointer events? The expected behavior in Chrome or Firefox should be:

```
if (browser supports touch events)
{
    return; // and do nothing
}
else if (browser supports MSpointerEvents or pointerEvents)
{
    emulate touch events;
}
```

**Comment by aichi** [comment]
Thanks for PR, unfortunately that would enable also Google Chrome and related browsers because `window.PointerEvent` is defined there. In this case I would suggest to use some other differentiator which is new/newer Edge specific, e.g. [Web Authentication API](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webauthenticationapi/?q=edge%3AShipped%20edge%3APrefixed).

There is `MSCredentials` object which can be checked.

**Comment by martinsuchan** [comment]
I was worried as well about this, but luckily the code already handles this situation on line https://github.com/aichi/Touchr/blob/master/js/touchr.js#L18
`if (IE_10 || (IE_11_PLUS && !('ontouchstart' in window))) {`
If the browser already supports Touch events, like Chrome or Firefox, then the emulation is not executed at all.

**Comment by aichi** [comment]
Great, you are right. Thanks for patience.
